{
 "title": "Resource Manager",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Blocked Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of blocked resource requests",
   "type": "timeseries",
   "description": "This should be empty. If it's large you are running into your resource manager limits.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(rcmgr_blocked_resources[$__rate_interval])"
    }
   ]
  },
  { "title": "Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "System Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rcmgr_streams{scope=\"system\"}",
     "legendFormat": "{{dir}} {{instance}}"
    }
   ]
  },
  {
   "title": "Transient Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rcmgr_streams{scope=\"transient\"}",
     "legendFormat": "{{dir}} {{instance}}"
    }
   ]
  },
  {
   "title": "Streams by service",
   "type": "timeseries",
   "description": "How many streams does each service have open",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rcmgr_streams{scope=\"service\"}",
     "legendFormat": "{{dir}} {{service}} {{instance}}"
    }
   ]
  },
  {
   "title": "Streams by protocol",
   "type": "timeseries",
   "description": "How many streams does each protocol have open.\n\nA protocol is similiar to a service except there may be many protocols for a single service. A service may have \nmultiple protocols for backwards compatibility. For example, bitswap the service is a single entity, but it supports bitswap protocols v1.1 and v1.2.\n\nA service is attached to a stream manually by the protocol developer. A service may be missing if there is no `StreamScope.SetService` call.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rcmgr_streams{scope=\"protocol\"}",
     "legendFormat": "{{dir}} {{protocol}} {{instance}}"
    }
   ]
  },
  {
   "title": "Streams per peer, aggregated",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, (rcmgr_peer_streams_bucket - rcmgr_previous_peer_streams_bucket)) - 0.1",
     "legendFormat": "p50 {{dir}} streams per peer – {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, (rcmgr_peer_streams_bucket - rcmgr_previous_peer_streams_bucket)) - 0.1",
     "legendFormat": "p90 {{dir}} streams per peer – {{instance}}"
    },
    {
     "expr": "histogram_quantile(1, (rcmgr_peer_streams_bucket - rcmgr_previous_peer_streams_bucket)) - 0.1",
     "legendFormat": "max {{dir}} streams per peer – {{instance}}"
    }
   ]
  },
  {
   "title": "Current inbound streams per peer histogram. Across all instances",
   "type": "bargauge",
   "description": "How many peers have N-0.1 streams open",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (rcmgr_peer_streams_bucket{dir=\"inbound\"}-rcmgr_previous_peer_streams_bucket{dir=\"inbound\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Current outbound streams per peer histogram. Across all instances",
   "type": "bargauge",
   "description": "How many peers have N-0.1 streams open",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (rcmgr_peer_streams_bucket{dir=\"outbound\"}-rcmgr_previous_peer_streams_bucket{dir=\"outbound\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "libp2p Connections",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "options": {
    "content": "# Libp2p Connections\n\nBroken down by [Resource Scope](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/resource-manager/README.md#resource-scopes). \nScopes represent what is imposing limits on this resource. For connections, we have three main scopes:\n\n1. System. The total number of connections owned by the process. Includes both application usable connections + the number of transient connections.\n2. Transient. The total number of connections that are being upgraded into usable connections in the process.\n3. Peer. The total number of connections associated with this peer. When a connection has this scope it is usable by the application.\n\nAn example of a System connection is a connection you can open a libp2p stream on and send data.\nA transient connection is not yet usable for application data since it may be negotiating \na security handshake or a multiplexer.\n\nConnections start in the transient scope and move over to the System and Peer scopes once they are ready to be used.\n\nIt would be unusual to see a lot of transient connections. It would also be unusal to see a peer with a lot of connections."
   }
  },
  {
   "title": "System Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rcmgr_connections{scope=\"system\"}",
     "legendFormat": "{{dir}} {{instance}}"
    }
   ]
  },
  {
   "title": "Transient Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rcmgr_connections{scope=\"transient\"}",
     "legendFormat": "{{dir}} {{instance}}"
    }
   ]
  },
  {
   "title": "Connections per Peer",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 72 },
   "options": {
    "content": "These are aggregated stats. They are grouped by buckets. Each bucket represents how many peers have N number of connections.\n\nDue to a quirk in [opencensus](https://github.com/census-instrumentation/opencensus-go/blob/v0.23.0/stats/view/aggregation_data.go#L195) the bucket values have to be a bit bigger than the integer values.\nSo subtract 0.1 from the number to get the true number of connections. e.g. If a peer has 3 connections, it'll be put in the 3.1 bucket. \n"
   }
  },
  {
   "title": "Connections per peer, aggregated",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, (rcmgr_peer_connections_bucket - rcmgr_previous_peer_connections_bucket)) - 0.1",
     "legendFormat": "p50 {{dir}} connections per peer – {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, (rcmgr_peer_connections_bucket - rcmgr_previous_peer_connections_bucket)) - 0.1",
     "legendFormat": "p90 {{dir}} connections per peer – {{instance}}"
    },
    {
     "expr": "histogram_quantile(1, (rcmgr_peer_connections_bucket - rcmgr_previous_peer_connections_bucket)) - 0.1",
     "legendFormat": "max {{dir}} connections per peer – {{instance}}"
    }
   ]
  },
  {
   "title": "Current inbound connections per peer histogram. Across all instances",
   "type": "bargauge",
   "description": "How many peers have N-0.1 connections open",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (rcmgr_peer_connections_bucket{dir=\"inbound\"}-rcmgr_previous_peer_connections_bucket{dir=\"inbound\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Curent outbound connections per peer histogram. Across all instances",
   "type": "bargauge",
   "description": "How many peers have N-0.1 connections open",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (rcmgr_peer_connections_bucket{dir=\"outbound\"}-rcmgr_previous_peer_connections_bucket{dir=\"outbound\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "System memory reservations",
   "type": "timeseries",
   "description": "As reported to Resource Manager",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rcmgr_memory{scope=\"system\"}",
     "legendFormat": "Bytes Reserved"
    }
   ]
  },
  {
   "title": "Memory reservations by protocol",
   "type": "timeseries",
   "description": "As reported to Resource Manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rcmgr_memory{scope=\"protocol\"}",
     "legendFormat": "{{protocol}} {{instance}}"
    }
   ]
  },
  {
   "title": "Memory reservations by service",
   "type": "timeseries",
   "description": "As reported to Resource Manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rcmgr_memory{scope=\"service\"}",
     "legendFormat": "{{service}} {{instance}}"
    }
   ]
  },
  {
   "title": "Memory reservations per peer, aggregated across all instances",
   "type": "timeseries",
   "description": "As reported to the resource manager",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rcmgr_peer_memory_bucket - rcmgr_previous_peer_memory_bucket)) - 0.1",
     "legendFormat": "p50 memory usage per peer"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rcmgr_peer_memory_bucket - rcmgr_previous_peer_memory_bucket)) - 0.1",
     "legendFormat": "p90 memory usage per peer"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rcmgr_peer_memory_bucket - rcmgr_previous_peer_memory_bucket)) - 0.1",
     "legendFormat": "max memory usage per peer"
    },
    {
     "expr": "sum(rcmgr_peer_memory_count-rcmgr_previous_peer_memory_count)",
     "legendFormat": "Number of peers aggregated"
    }
   ]
  },
  { "title": "File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "FDs in use",
   "type": "timeseries",
   "description": "As reported to the resource manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    { "expr": "rcmgr_fds", "legendFormat": "{{scope}} {{instance}}" }
   ]
  }
 ]
}