// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: payload.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NoiseExtensions struct {
	WebtransportCerthashes [][]byte `protobuf:"bytes,1,rep,name=webtransport_certhashes,json=webtransportCerthashes" json:"webtransport_certhashes,omitempty"`
	StreamMuxers           []string `protobuf:"bytes,2,rep,name=stream_muxers,json=streamMuxers" json:"stream_muxers,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *NoiseExtensions) Reset()         { *m = NoiseExtensions{} }
func (m *NoiseExtensions) String() string { return proto.CompactTextString(m) }
func (*NoiseExtensions) ProtoMessage()    {}
func (*NoiseExtensions) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0}
}
func (m *NoiseExtensions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoiseExtensions.Unmarshal(m, b)
}
func (m *NoiseExtensions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoiseExtensions.Marshal(b, m, deterministic)
}
func (m *NoiseExtensions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoiseExtensions.Merge(m, src)
}
func (m *NoiseExtensions) XXX_Size() int {
	return xxx_messageInfo_NoiseExtensions.Size(m)
}
func (m *NoiseExtensions) XXX_DiscardUnknown() {
	xxx_messageInfo_NoiseExtensions.DiscardUnknown(m)
}

var xxx_messageInfo_NoiseExtensions proto.InternalMessageInfo

func (m *NoiseExtensions) GetWebtransportCerthashes() [][]byte {
	if m != nil {
		return m.WebtransportCerthashes
	}
	return nil
}

func (m *NoiseExtensions) GetStreamMuxers() []string {
	if m != nil {
		return m.StreamMuxers
	}
	return nil
}

type NoiseHandshakePayload struct {
	IdentityKey          []byte           `protobuf:"bytes,1,opt,name=identity_key,json=identityKey" json:"identity_key,omitempty"`
	IdentitySig          []byte           `protobuf:"bytes,2,opt,name=identity_sig,json=identitySig" json:"identity_sig,omitempty"`
	Extensions           *NoiseExtensions `protobuf:"bytes,4,opt,name=extensions" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NoiseHandshakePayload) Reset()         { *m = NoiseHandshakePayload{} }
func (m *NoiseHandshakePayload) String() string { return proto.CompactTextString(m) }
func (*NoiseHandshakePayload) ProtoMessage()    {}
func (*NoiseHandshakePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{1}
}
func (m *NoiseHandshakePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoiseHandshakePayload.Unmarshal(m, b)
}
func (m *NoiseHandshakePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoiseHandshakePayload.Marshal(b, m, deterministic)
}
func (m *NoiseHandshakePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoiseHandshakePayload.Merge(m, src)
}
func (m *NoiseHandshakePayload) XXX_Size() int {
	return xxx_messageInfo_NoiseHandshakePayload.Size(m)
}
func (m *NoiseHandshakePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_NoiseHandshakePayload.DiscardUnknown(m)
}

var xxx_messageInfo_NoiseHandshakePayload proto.InternalMessageInfo

func (m *NoiseHandshakePayload) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *NoiseHandshakePayload) GetIdentitySig() []byte {
	if m != nil {
		return m.IdentitySig
	}
	return nil
}

func (m *NoiseHandshakePayload) GetExtensions() *NoiseExtensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func init() {
	proto.RegisterType((*NoiseExtensions)(nil), "pb.NoiseExtensions")
	proto.RegisterType((*NoiseHandshakePayload)(nil), "pb.NoiseHandshakePayload")
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor_678c914f1bee6d56) }

var fileDescriptor_678c914f1bee6d56 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xc9, 0xd6, 0x8b, 0xd3, 0x14, 0x21, 0xa2, 0xe6, 0x18, 0xeb, 0x25, 0xa7, 0x3d, 0xe8,
	0xc1, 0x07, 0x10, 0x41, 0x10, 0x45, 0xe2, 0x03, 0x2c, 0x59, 0x77, 0xe8, 0x86, 0xda, 0x24, 0x64,
	0x46, 0x6c, 0x5e, 0xc3, 0x27, 0x16, 0x5a, 0x2c, 0x5d, 0xaf, 0xdf, 0xff, 0xc1, 0xcc, 0x07, 0x8b,
	0xec, 0xeb, 0x67, 0xf2, 0x43, 0x9b, 0x4b, 0xe2, 0xa4, 0x9a, 0xdc, 0x2f, 0x13, 0x9c, 0xbd, 0xa6,
	0x40, 0xf8, 0xb8, 0x65, 0x8c, 0x14, 0x52, 0x24, 0x75, 0x0f, 0x57, 0xdf, 0xd8, 0x73, 0xf1, 0x91,
	0x72, 0x2a, 0xdc, 0x7d, 0x60, 0xe1, 0xd1, 0xd3, 0x88, 0xa4, 0x85, 0x99, 0x59, 0xe9, 0x2e, 0x8f,
	0xe7, 0x87, 0xc3, 0xaa, 0x6e, 0x60, 0x41, 0x5c, 0xd0, 0x6f, 0xba, 0xcd, 0xd7, 0x16, 0x0b, 0xe9,
	0xc6, 0xcc, 0xec, 0xa9, 0x93, 0x7b, 0xf8, 0xb2, 0x63, 0xcb, 0x1f, 0x01, 0x17, 0xbb, 0x8b, 0x4f,
	0x3e, 0x0e, 0x34, 0xfa, 0x35, 0xbe, 0xed, 0x9f, 0x52, 0xd7, 0x20, 0xc3, 0x80, 0x91, 0x03, 0xd7,
	0x6e, 0x8d, 0x55, 0x0b, 0x23, 0xac, 0x74, 0xf3, 0x3f, 0xf6, 0x8c, 0x75, 0xa2, 0x50, 0x58, 0xe9,
	0x66, 0xaa, 0xbc, 0x87, 0x95, 0xba, 0x03, 0xc0, 0x43, 0x8b, 0x3e, 0x31, 0xc2, 0xce, 0x6f, 0xcf,
	0xdb, 0xdc, 0xb7, 0xff, 0x32, 0xdd, 0x91, 0xf6, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x51, 0xda,
	0x51, 0x19, 0x01, 0x00, 0x00,
}

var (
	ErrInvalidLengthPayload        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPayload          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPayload = fmt.Errorf("proto: unexpected end of group")
)
