{
 "title": "libp2p Hole Punch",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "DCUtR initiator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hole Punches: TCP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (outcome) (increase(libp2p_holepunch_address_outcomes_total {side=\"initiator\", transport=\"tcp\", outcome=~\"success|failed\"}[$__range]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Hole Punches: QUIC",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (outcome) (increase(libp2p_holepunch_address_outcomes_total {side=\"initiator\", transport=~\"quic|quic-v1\", outcome=~\"success|failed\"}[$__range]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Hole Punches: Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (outcome) (increase(libp2p_holepunch_outcomes_total{side=\"initiator\"}[$__range]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Direct Dials ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(libp2p_holepunch_direct_dials_total[$__rate_interval])",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Holepunches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (outcome) (libp2p_holepunch_outcomes_total{side=\"initiator\"}) - (sum by (outcome)(libp2p_holepunch_outcomes_total{side=\"initiator\"} offset $__interval) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DCUtR Receiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Hole Punches: QUIC ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (outcome) (increase(libp2p_holepunch_address_outcomes_total {side=\"receiver\", transport=~\"quic|quic-v1\", outcome=~\"success|failed\"}[$__range]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Hole Punches: TCP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (outcome) (increase(libp2p_holepunch_address_outcomes_total {side=\"receiver\", transport=\"tcp\", outcome=~\"success|failed\"}[$__range]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Hole Punches: Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (outcome) (increase(libp2p_holepunch_outcomes_total{side=\"receiver\"}[$__range]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Holepunches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "(sum by (outcome) (libp2p_holepunch_outcomes_total{side=\"receiver\"})) - (sum by (outcome)(libp2p_holepunch_outcomes_total{side=\"receiver\"} offset $__interval) or vector(0))",
     "legendFormat": "{{outcome}}"
    }
   ]
  }
 ]
}