// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: pb/autonat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DialResponse_ResponseStatus int32

const (
	DialResponse_ResponseStatus_OK DialResponse_ResponseStatus = 0
	DialResponse_E_BAD_REQUEST     DialResponse_ResponseStatus = 100
	DialResponse_E_REQUEST_REFUSED DialResponse_ResponseStatus = 101
	DialResponse_E_INTERNAL_ERROR  DialResponse_ResponseStatus = 300
)

// Enum value maps for DialResponse_ResponseStatus.
var (
	DialResponse_ResponseStatus_name = map[int32]string{
		0:   "ResponseStatus_OK",
		100: "E_BAD_REQUEST",
		101: "E_REQUEST_REFUSED",
		300: "E_INTERNAL_ERROR",
	}
	DialResponse_ResponseStatus_value = map[string]int32{
		"ResponseStatus_OK": 0,
		"E_BAD_REQUEST":     100,
		"E_REQUEST_REFUSED": 101,
		"E_INTERNAL_ERROR":  300,
	}
)

func (x DialResponse_ResponseStatus) Enum() *DialResponse_ResponseStatus {
	p := new(DialResponse_ResponseStatus)
	*p = x
	return p
}

func (x DialResponse_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialResponse_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_autonat_proto_enumTypes[0].Descriptor()
}

func (DialResponse_ResponseStatus) Type() protoreflect.EnumType {
	return &file_pb_autonat_proto_enumTypes[0]
}

func (x DialResponse_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialResponse_ResponseStatus.Descriptor instead.
func (DialResponse_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_autonat_proto_rawDescGZIP(), []int{3, 0}
}

type DialResponse_DialStatus int32

const (
	DialResponse_DialStaus_OK              DialResponse_DialStatus = 0
	DialResponse_E_DIAL_ERROR              DialResponse_DialStatus = 100
	DialResponse_E_CONN_UPGRADE_FAILED     DialResponse_DialStatus = 101
	DialResponse_E_ATTEMPT_ERROR           DialResponse_DialStatus = 102
	DialResponse_E_DIAL_REFUSED            DialResponse_DialStatus = 200
	DialResponse_E_TRANSPORT_NOT_SUPPORTED DialResponse_DialStatus = 300
	DialResponse_E_ADDRESS_UNKNOWN         DialResponse_DialStatus = 301
)

// Enum value maps for DialResponse_DialStatus.
var (
	DialResponse_DialStatus_name = map[int32]string{
		0:   "DialStaus_OK",
		100: "E_DIAL_ERROR",
		101: "E_CONN_UPGRADE_FAILED",
		102: "E_ATTEMPT_ERROR",
		200: "E_DIAL_REFUSED",
		300: "E_TRANSPORT_NOT_SUPPORTED",
		301: "E_ADDRESS_UNKNOWN",
	}
	DialResponse_DialStatus_value = map[string]int32{
		"DialStaus_OK":              0,
		"E_DIAL_ERROR":              100,
		"E_CONN_UPGRADE_FAILED":     101,
		"E_ATTEMPT_ERROR":           102,
		"E_DIAL_REFUSED":            200,
		"E_TRANSPORT_NOT_SUPPORTED": 300,
		"E_ADDRESS_UNKNOWN":         301,
	}
)

func (x DialResponse_DialStatus) Enum() *DialResponse_DialStatus {
	p := new(DialResponse_DialStatus)
	*p = x
	return p
}

func (x DialResponse_DialStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialResponse_DialStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_autonat_proto_enumTypes[1].Descriptor()
}

func (DialResponse_DialStatus) Type() protoreflect.EnumType {
	return &file_pb_autonat_proto_enumTypes[1]
}

func (x DialResponse_DialStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialResponse_DialStatus.Descriptor instead.
func (DialResponse_DialStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_autonat_proto_rawDescGZIP(), []int{3, 1}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*Message_DialRequest
	//	*Message_DialResponse
	//	*Message_DialDataRequest
	Msg isMessage_Msg `protobuf_oneof:"msg"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_autonat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autonat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pb_autonat_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetMsg() isMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *Message) GetDialRequest() *DialRequest {
	if x, ok := x.GetMsg().(*Message_DialRequest); ok {
		return x.DialRequest
	}
	return nil
}

func (x *Message) GetDialResponse() *DialResponse {
	if x, ok := x.GetMsg().(*Message_DialResponse); ok {
		return x.DialResponse
	}
	return nil
}

func (x *Message) GetDialDataRequest() *DialDataRequest {
	if x, ok := x.GetMsg().(*Message_DialDataRequest); ok {
		return x.DialDataRequest
	}
	return nil
}

type isMessage_Msg interface {
	isMessage_Msg()
}

type Message_DialRequest struct {
	DialRequest *DialRequest `protobuf:"bytes,1,opt,name=dialRequest,proto3,oneof"`
}

type Message_DialResponse struct {
	DialResponse *DialResponse `protobuf:"bytes,2,opt,name=dialResponse,proto3,oneof"`
}

type Message_DialDataRequest struct {
	DialDataRequest *DialDataRequest `protobuf:"bytes,3,opt,name=dialDataRequest,proto3,oneof"`
}

func (*Message_DialRequest) isMessage_Msg() {}

func (*Message_DialResponse) isMessage_Msg() {}

func (*Message_DialDataRequest) isMessage_Msg() {}

type DialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addrs [][]byte `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Nonce uint64   `protobuf:"fixed64,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *DialRequest) Reset() {
	*x = DialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_autonat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialRequest) ProtoMessage() {}

func (x *DialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autonat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialRequest.ProtoReflect.Descriptor instead.
func (*DialRequest) Descriptor() ([]byte, []int) {
	return file_pb_autonat_proto_rawDescGZIP(), []int{1}
}

func (x *DialRequest) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *DialRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type DialDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddrIdx  uint32 `protobuf:"varint,1,opt,name=addrIdx,proto3" json:"addrIdx,omitempty"`
	NumBytes uint64 `protobuf:"varint,2,opt,name=numBytes,proto3" json:"numBytes,omitempty"`
}

func (x *DialDataRequest) Reset() {
	*x = DialDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_autonat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialDataRequest) ProtoMessage() {}

func (x *DialDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autonat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialDataRequest.ProtoReflect.Descriptor instead.
func (*DialDataRequest) Descriptor() ([]byte, []int) {
	return file_pb_autonat_proto_rawDescGZIP(), []int{2}
}

func (x *DialDataRequest) GetAddrIdx() uint32 {
	if x != nil {
		return x.AddrIdx
	}
	return 0
}

func (x *DialDataRequest) GetNumBytes() uint64 {
	if x != nil {
		return x.NumBytes
	}
	return 0
}

type DialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       DialResponse_ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=autonatv2.pb.DialResponse_ResponseStatus" json:"status,omitempty"`
	DialStatuses []DialResponse_DialStatus   `protobuf:"varint,2,rep,packed,name=dialStatuses,proto3,enum=autonatv2.pb.DialResponse_DialStatus" json:"dialStatuses,omitempty"`
}

func (x *DialResponse) Reset() {
	*x = DialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_autonat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialResponse) ProtoMessage() {}

func (x *DialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autonat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialResponse.ProtoReflect.Descriptor instead.
func (*DialResponse) Descriptor() ([]byte, []int) {
	return file_pb_autonat_proto_rawDescGZIP(), []int{3}
}

func (x *DialResponse) GetStatus() DialResponse_ResponseStatus {
	if x != nil {
		return x.Status
	}
	return DialResponse_ResponseStatus_OK
}

func (x *DialResponse) GetDialStatuses() []DialResponse_DialStatus {
	if x != nil {
		return x.DialStatuses
	}
	return nil
}

type DialAttempt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce uint64 `protobuf:"fixed64,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *DialAttempt) Reset() {
	*x = DialAttempt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_autonat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialAttempt) ProtoMessage() {}

func (x *DialAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autonat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialAttempt.ProtoReflect.Descriptor instead.
func (*DialAttempt) Descriptor() ([]byte, []int) {
	return file_pb_autonat_proto_rawDescGZIP(), []int{4}
}

func (x *DialAttempt) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_pb_autonat_proto protoreflect.FileDescriptor

var file_pb_autonat_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32, 0x2e, 0x70, 0x62,
	0x22, 0xdc, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x0b,
	0x64, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b,
	0x64, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x0c, 0x64,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x0c, 0x64, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a,
	0x0f, 0x64, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74,
	0x76, 0x32, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x64, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x39, 0x0a, 0x0b, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x61,
	0x64, 0x64, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x47, 0x0a, 0x0f, 0x44, 0x69,
	0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x49, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x49, 0x64, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x22, 0xb6, 0x03, 0x0a, 0x0c, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x49, 0x0a, 0x0c, 0x64, 0x69, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x25, 0x2e,
	0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x64, 0x69, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x65, 0x73, 0x22, 0x68, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x45,
	0x5f, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x64, 0x12, 0x15,
	0x0a, 0x11, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x46, 0x55,
	0x53, 0x45, 0x44, 0x10, 0x65, 0x12, 0x15, 0x0a, 0x10, 0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xac, 0x02, 0x22, 0xad, 0x01, 0x0a,
	0x0a, 0x44, 0x69, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x44,
	0x69, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x75, 0x73, 0x5f, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x10, 0x0a,
	0x0c, 0x45, 0x5f, 0x44, 0x49, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x64, 0x12,
	0x19, 0x0a, 0x15, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x55, 0x50, 0x47, 0x52, 0x41, 0x44,
	0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x5f,
	0x41, 0x54, 0x54, 0x45, 0x4d, 0x50, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x66, 0x12,
	0x13, 0x0a, 0x0e, 0x45, 0x5f, 0x44, 0x49, 0x41, 0x4c, 0x5f, 0x52, 0x45, 0x46, 0x55, 0x53, 0x45,
	0x44, 0x10, 0xc8, 0x01, 0x12, 0x1e, 0x0a, 0x19, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50,
	0x4f, 0x52, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45,
	0x44, 0x10, 0xac, 0x02, 0x12, 0x16, 0x0a, 0x11, 0x45, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53,
	0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0xad, 0x02, 0x22, 0x23, 0x0a, 0x0b,
	0x44, 0x69, 0x61, 0x6c, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_autonat_proto_rawDescOnce sync.Once
	file_pb_autonat_proto_rawDescData = file_pb_autonat_proto_rawDesc
)

func file_pb_autonat_proto_rawDescGZIP() []byte {
	file_pb_autonat_proto_rawDescOnce.Do(func() {
		file_pb_autonat_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_autonat_proto_rawDescData)
	})
	return file_pb_autonat_proto_rawDescData
}

var file_pb_autonat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_autonat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_autonat_proto_goTypes = []interface{}{
	(DialResponse_ResponseStatus)(0), // 0: autonatv2.pb.DialResponse.ResponseStatus
	(DialResponse_DialStatus)(0),     // 1: autonatv2.pb.DialResponse.DialStatus
	(*Message)(nil),                  // 2: autonatv2.pb.Message
	(*DialRequest)(nil),              // 3: autonatv2.pb.DialRequest
	(*DialDataRequest)(nil),          // 4: autonatv2.pb.DialDataRequest
	(*DialResponse)(nil),             // 5: autonatv2.pb.DialResponse
	(*DialAttempt)(nil),              // 6: autonatv2.pb.DialAttempt
}
var file_pb_autonat_proto_depIdxs = []int32{
	3, // 0: autonatv2.pb.Message.dialRequest:type_name -> autonatv2.pb.DialRequest
	5, // 1: autonatv2.pb.Message.dialResponse:type_name -> autonatv2.pb.DialResponse
	4, // 2: autonatv2.pb.Message.dialDataRequest:type_name -> autonatv2.pb.DialDataRequest
	0, // 3: autonatv2.pb.DialResponse.status:type_name -> autonatv2.pb.DialResponse.ResponseStatus
	1, // 4: autonatv2.pb.DialResponse.dialStatuses:type_name -> autonatv2.pb.DialResponse.DialStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pb_autonat_proto_init() }
func file_pb_autonat_proto_init() {
	if File_pb_autonat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_autonat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_autonat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_autonat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_autonat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_autonat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialAttempt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_autonat_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_DialRequest)(nil),
		(*Message_DialResponse)(nil),
		(*Message_DialDataRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_autonat_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_autonat_proto_goTypes,
		DependencyIndexes: file_pb_autonat_proto_depIdxs,
		EnumInfos:         file_pb_autonat_proto_enumTypes,
		MessageInfos:      file_pb_autonat_proto_msgTypes,
	}.Build()
	File_pb_autonat_proto = out.File
	file_pb_autonat_proto_rawDesc = nil
	file_pb_autonat_proto_goTypes = nil
	file_pb_autonat_proto_depIdxs = nil
}
