// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: pbv2/autonat.proto

package pbv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DialStatus int32

const (
	DialStatus_E_INTERNAL_ERROR DialStatus = 0 // Default value to force servers to explicitly set the status
	DialStatus_E_DIAL_REFUSED   DialStatus = 100
	DialStatus_E_DIAL_ERROR     DialStatus = 101
	DialStatus_E_ATTEMPT_ERROR  DialStatus = 102
	DialStatus_OK               DialStatus = 200
)

// Enum value maps for DialStatus.
var (
	DialStatus_name = map[int32]string{
		0:   "E_INTERNAL_ERROR",
		100: "E_DIAL_REFUSED",
		101: "E_DIAL_ERROR",
		102: "E_ATTEMPT_ERROR",
		200: "OK",
	}
	DialStatus_value = map[string]int32{
		"E_INTERNAL_ERROR": 0,
		"E_DIAL_REFUSED":   100,
		"E_DIAL_ERROR":     101,
		"E_ATTEMPT_ERROR":  102,
		"OK":               200,
	}
)

func (x DialStatus) Enum() *DialStatus {
	p := new(DialStatus)
	*p = x
	return p
}

func (x DialStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pbv2_autonat_proto_enumTypes[0].Descriptor()
}

func (DialStatus) Type() protoreflect.EnumType {
	return &file_pbv2_autonat_proto_enumTypes[0]
}

func (x DialStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialStatus.Descriptor instead.
func (DialStatus) EnumDescriptor() ([]byte, []int) {
	return file_pbv2_autonat_proto_rawDescGZIP(), []int{0}
}

type DialResponse_ResponseStatus int32

const (
	DialResponse_E_INTERNAL_ERROR   DialResponse_ResponseStatus = 0
	DialResponse_E_REQUEST_REJECTED DialResponse_ResponseStatus = 100
	DialResponse_ResponseStatus_OK  DialResponse_ResponseStatus = 200
)

// Enum value maps for DialResponse_ResponseStatus.
var (
	DialResponse_ResponseStatus_name = map[int32]string{
		0:   "E_INTERNAL_ERROR",
		100: "E_REQUEST_REJECTED",
		200: "ResponseStatus_OK",
	}
	DialResponse_ResponseStatus_value = map[string]int32{
		"E_INTERNAL_ERROR":   0,
		"E_REQUEST_REJECTED": 100,
		"ResponseStatus_OK":  200,
	}
)

func (x DialResponse_ResponseStatus) Enum() *DialResponse_ResponseStatus {
	p := new(DialResponse_ResponseStatus)
	*p = x
	return p
}

func (x DialResponse_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DialResponse_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pbv2_autonat_proto_enumTypes[1].Descriptor()
}

func (DialResponse_ResponseStatus) Type() protoreflect.EnumType {
	return &file_pbv2_autonat_proto_enumTypes[1]
}

func (x DialResponse_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DialResponse_ResponseStatus.Descriptor instead.
func (DialResponse_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_pbv2_autonat_proto_rawDescGZIP(), []int{3, 0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*Message_DialRequest
	//	*Message_DialResponse
	//	*Message_DialDataRequest
	//	*Message_DialDataResponse
	Msg isMessage_Msg `protobuf_oneof:"msg"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbv2_autonat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pbv2_autonat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pbv2_autonat_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetMsg() isMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *Message) GetDialRequest() *DialRequest {
	if x, ok := x.GetMsg().(*Message_DialRequest); ok {
		return x.DialRequest
	}
	return nil
}

func (x *Message) GetDialResponse() *DialResponse {
	if x, ok := x.GetMsg().(*Message_DialResponse); ok {
		return x.DialResponse
	}
	return nil
}

func (x *Message) GetDialDataRequest() *DialDataRequest {
	if x, ok := x.GetMsg().(*Message_DialDataRequest); ok {
		return x.DialDataRequest
	}
	return nil
}

func (x *Message) GetDialDataResponse() *DialDataResponse {
	if x, ok := x.GetMsg().(*Message_DialDataResponse); ok {
		return x.DialDataResponse
	}
	return nil
}

type isMessage_Msg interface {
	isMessage_Msg()
}

type Message_DialRequest struct {
	DialRequest *DialRequest `protobuf:"bytes,1,opt,name=dialRequest,proto3,oneof"`
}

type Message_DialResponse struct {
	DialResponse *DialResponse `protobuf:"bytes,2,opt,name=dialResponse,proto3,oneof"`
}

type Message_DialDataRequest struct {
	DialDataRequest *DialDataRequest `protobuf:"bytes,3,opt,name=dialDataRequest,proto3,oneof"`
}

type Message_DialDataResponse struct {
	DialDataResponse *DialDataResponse `protobuf:"bytes,4,opt,name=dialDataResponse,proto3,oneof"`
}

func (*Message_DialRequest) isMessage_Msg() {}

func (*Message_DialResponse) isMessage_Msg() {}

func (*Message_DialDataRequest) isMessage_Msg() {}

func (*Message_DialDataResponse) isMessage_Msg() {}

type DialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addrs [][]byte `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Nonce uint64   `protobuf:"fixed64,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *DialRequest) Reset() {
	*x = DialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbv2_autonat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialRequest) ProtoMessage() {}

func (x *DialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbv2_autonat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialRequest.ProtoReflect.Descriptor instead.
func (*DialRequest) Descriptor() ([]byte, []int) {
	return file_pbv2_autonat_proto_rawDescGZIP(), []int{1}
}

func (x *DialRequest) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *DialRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type DialDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddrIdx  uint32 `protobuf:"varint,1,opt,name=addrIdx,proto3" json:"addrIdx,omitempty"`
	NumBytes uint64 `protobuf:"varint,2,opt,name=numBytes,proto3" json:"numBytes,omitempty"`
}

func (x *DialDataRequest) Reset() {
	*x = DialDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbv2_autonat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialDataRequest) ProtoMessage() {}

func (x *DialDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbv2_autonat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialDataRequest.ProtoReflect.Descriptor instead.
func (*DialDataRequest) Descriptor() ([]byte, []int) {
	return file_pbv2_autonat_proto_rawDescGZIP(), []int{2}
}

func (x *DialDataRequest) GetAddrIdx() uint32 {
	if x != nil {
		return x.AddrIdx
	}
	return 0
}

func (x *DialDataRequest) GetNumBytes() uint64 {
	if x != nil {
		return x.NumBytes
	}
	return 0
}

type DialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     DialResponse_ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=autonatv2.pbv2.DialResponse_ResponseStatus" json:"status,omitempty"`
	AddrIdx    uint32                      `protobuf:"varint,2,opt,name=addrIdx,proto3" json:"addrIdx,omitempty"`
	DialStatus DialStatus                  `protobuf:"varint,3,opt,name=dialStatus,proto3,enum=autonatv2.pbv2.DialStatus" json:"dialStatus,omitempty"`
}

func (x *DialResponse) Reset() {
	*x = DialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbv2_autonat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialResponse) ProtoMessage() {}

func (x *DialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pbv2_autonat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialResponse.ProtoReflect.Descriptor instead.
func (*DialResponse) Descriptor() ([]byte, []int) {
	return file_pbv2_autonat_proto_rawDescGZIP(), []int{3}
}

func (x *DialResponse) GetStatus() DialResponse_ResponseStatus {
	if x != nil {
		return x.Status
	}
	return DialResponse_E_INTERNAL_ERROR
}

func (x *DialResponse) GetAddrIdx() uint32 {
	if x != nil {
		return x.AddrIdx
	}
	return 0
}

func (x *DialResponse) GetDialStatus() DialStatus {
	if x != nil {
		return x.DialStatus
	}
	return DialStatus_E_INTERNAL_ERROR
}

type DialDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DialDataResponse) Reset() {
	*x = DialDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbv2_autonat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialDataResponse) ProtoMessage() {}

func (x *DialDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pbv2_autonat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialDataResponse.ProtoReflect.Descriptor instead.
func (*DialDataResponse) Descriptor() ([]byte, []int) {
	return file_pbv2_autonat_proto_rawDescGZIP(), []int{4}
}

func (x *DialDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DialAttempt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce uint64 `protobuf:"fixed64,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *DialAttempt) Reset() {
	*x = DialAttempt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbv2_autonat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialAttempt) ProtoMessage() {}

func (x *DialAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_pbv2_autonat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialAttempt.ProtoReflect.Descriptor instead.
func (*DialAttempt) Descriptor() ([]byte, []int) {
	return file_pbv2_autonat_proto_rawDescGZIP(), []int{5}
}

func (x *DialAttempt) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_pbv2_autonat_proto protoreflect.FileDescriptor

var file_pbv2_autonat_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x76, 0x32, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32, 0x2e,
	0x70, 0x62, 0x76, 0x32, 0x22, 0xb2, 0x02, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x3f, 0x0a, 0x0b, 0x64, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76,
	0x32, 0x2e, 0x70, 0x62, 0x76, 0x32, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x42, 0x0a, 0x0c, 0x64, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61,
	0x74, 0x76, 0x32, 0x2e, 0x70, 0x62, 0x76, 0x32, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x64, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32, 0x2e, 0x70, 0x62, 0x76, 0x32, 0x2e,
	0x44, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x0f, 0x64, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x4e, 0x0a, 0x10, 0x64, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61,
	0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32, 0x2e, 0x70, 0x62, 0x76, 0x32, 0x2e, 0x44, 0x69,
	0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x10, 0x64, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x39, 0x0a, 0x0b, 0x44, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x22, 0x47, 0x0a, 0x0f, 0x44, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x49,
	0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x49, 0x64,
	0x78, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x81, 0x02,
	0x0a, 0x0c, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b,
	0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32, 0x2e, 0x70, 0x62, 0x76, 0x32, 0x2e,
	0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x49, 0x64, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x49, 0x64, 0x78, 0x12, 0x3a, 0x0a,
	0x0a, 0x64, 0x69, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x61, 0x74, 0x76, 0x32, 0x2e, 0x70, 0x62,
	0x76, 0x32, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x64,
	0x69, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x56, 0x0a, 0x0e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x10, 0x45,
	0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x52,
	0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x64, 0x12, 0x16, 0x0a, 0x11, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x4f, 0x4b, 0x10, 0xc8,
	0x01, 0x22, 0x26, 0x0a, 0x10, 0x44, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x23, 0x0a, 0x0b, 0x44, 0x69, 0x61,
	0x6c, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x2a, 0x66,
	0x0a, 0x0a, 0x44, 0x69, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x10,
	0x45, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x5f, 0x44, 0x49, 0x41, 0x4c, 0x5f, 0x52, 0x45, 0x46,
	0x55, 0x53, 0x45, 0x44, 0x10, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x5f, 0x44, 0x49, 0x41, 0x4c,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x5f, 0x41, 0x54,
	0x54, 0x45, 0x4d, 0x50, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x66, 0x12, 0x07, 0x0a,
	0x02, 0x4f, 0x4b, 0x10, 0xc8, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbv2_autonat_proto_rawDescOnce sync.Once
	file_pbv2_autonat_proto_rawDescData = file_pbv2_autonat_proto_rawDesc
)

func file_pbv2_autonat_proto_rawDescGZIP() []byte {
	file_pbv2_autonat_proto_rawDescOnce.Do(func() {
		file_pbv2_autonat_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbv2_autonat_proto_rawDescData)
	})
	return file_pbv2_autonat_proto_rawDescData
}

var file_pbv2_autonat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pbv2_autonat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pbv2_autonat_proto_goTypes = []interface{}{
	(DialStatus)(0),                  // 0: autonatv2.pbv2.DialStatus
	(DialResponse_ResponseStatus)(0), // 1: autonatv2.pbv2.DialResponse.ResponseStatus
	(*Message)(nil),                  // 2: autonatv2.pbv2.Message
	(*DialRequest)(nil),              // 3: autonatv2.pbv2.DialRequest
	(*DialDataRequest)(nil),          // 4: autonatv2.pbv2.DialDataRequest
	(*DialResponse)(nil),             // 5: autonatv2.pbv2.DialResponse
	(*DialDataResponse)(nil),         // 6: autonatv2.pbv2.DialDataResponse
	(*DialAttempt)(nil),              // 7: autonatv2.pbv2.DialAttempt
}
var file_pbv2_autonat_proto_depIdxs = []int32{
	3, // 0: autonatv2.pbv2.Message.dialRequest:type_name -> autonatv2.pbv2.DialRequest
	5, // 1: autonatv2.pbv2.Message.dialResponse:type_name -> autonatv2.pbv2.DialResponse
	4, // 2: autonatv2.pbv2.Message.dialDataRequest:type_name -> autonatv2.pbv2.DialDataRequest
	6, // 3: autonatv2.pbv2.Message.dialDataResponse:type_name -> autonatv2.pbv2.DialDataResponse
	1, // 4: autonatv2.pbv2.DialResponse.status:type_name -> autonatv2.pbv2.DialResponse.ResponseStatus
	0, // 5: autonatv2.pbv2.DialResponse.dialStatus:type_name -> autonatv2.pbv2.DialStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pbv2_autonat_proto_init() }
func file_pbv2_autonat_proto_init() {
	if File_pbv2_autonat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbv2_autonat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbv2_autonat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbv2_autonat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbv2_autonat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbv2_autonat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbv2_autonat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialAttempt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pbv2_autonat_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_DialRequest)(nil),
		(*Message_DialResponse)(nil),
		(*Message_DialDataRequest)(nil),
		(*Message_DialDataResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbv2_autonat_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbv2_autonat_proto_goTypes,
		DependencyIndexes: file_pbv2_autonat_proto_depIdxs,
		EnumInfos:         file_pbv2_autonat_proto_enumTypes,
		MessageInfos:      file_pbv2_autonat_proto_msgTypes,
	}.Build()
	File_pbv2_autonat_proto = out.File
	file_pbv2_autonat_proto_rawDesc = nil
	file_pbv2_autonat_proto_goTypes = nil
	file_pbv2_autonat_proto_depIdxs = nil
}
